% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{adjustbox}
\usepackage{hyperref}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Assignment 1: California Spiny Lobster Abundance (Panulirus Interruptus)},
  pdfauthor={EDS 241},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment 1: California Spiny Lobster Abundance (\emph{Panulirus
Interruptus})}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Assessing the Impact of Marine Protected Areas (MPAs) at 5
Reef Sites in Santa Barbara County}
\author{EDS 241}
\date{1/8/2024 (Due 1/22)}

\begin{document}
\maketitle

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{figures/spiny2.jpg}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{Assignment instructions:}\label{assignment-instructions}

\begin{itemize}
\item
  Working with partners to troubleshoot code and concepts is encouraged!
  If you work with a partner, please list their name next to yours at
  the top of your assignment so Annie and I can easily see who
  collaborated.
\item
  All written responses must be written independently (\textbf{in your
  own words}).
\item
  Please follow the question prompts carefully and include only the
  information each question asks in your submitted responses.
\item
  Submit both your knitted document and the associated
  \texttt{RMarkdown} or \texttt{Quarto} file.
\item
  Your knitted presentation should meet the quality you'd submit to
  research colleagues or feel confident sharing publicly. Refer to the
  rubric for details about presentation standards.
\end{itemize}

\textbf{Assignment submission (YOUR NAME):} \_\_\_\_\_Bailey
Jørgensen\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(here)}
\FunctionTok{library}\NormalTok{(janitor)}
\FunctionTok{library}\NormalTok{(estimatr)  }
\FunctionTok{library}\NormalTok{(performance)}
\FunctionTok{library}\NormalTok{(jtools)}
\FunctionTok{library}\NormalTok{(gt)}
\FunctionTok{library}\NormalTok{(gtsummary)}
\FunctionTok{library}\NormalTok{(MASS) }\DocumentationTok{\#\# }\AlertTok{NOTE}\DocumentationTok{: The \textasciigrave{}select()\textasciigrave{} function is masked. Use: \textasciigrave{}dplyr::select()\textasciigrave{} \#\#}
\FunctionTok{library}\NormalTok{(interactions) }
\FunctionTok{library}\NormalTok{(ggridges)}
\FunctionTok{library}\NormalTok{(beeswarm)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\paragraph{DATA SOURCE:}\label{data-source}

Reed D. 2019. SBC LTER: Reef: Abundance, size and fishing effort for
California Spiny Lobster (Panulirus interruptus), ongoing since 2012.
Environmental Data Initiative.
\url{https://doi.org/10.6073/pasta/a593a675d644fdefb736750b291579a0}.
Dataset accessed 11/17/2019.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Introduction}}{Introduction}}\label{introduction}

You're about to dive into some deep data collected from five reef sites
in Santa Barbara County, all about the abundance of California spiny
lobsters! 🦞 Data was gathered by divers annually from 2012 to 2018
across Naples, Mohawk, Isla Vista, Carpinteria, and Arroyo Quemado
reefs.

Why lobsters? Well, this sample provides an opportunity to evaluate the
impact of Marine Protected Areas (MPAs) established on January 1, 2012
(Reed, 2019). Of these five reefs, Naples, and Isla Vista are MPAs,
while the other three are not protected (non-MPAs). Comparing lobster
health between these protected and non-protected areas gives us the
chance to study how commercial and recreational fishing might impact
these ecosystems.

We will consider the MPA sites the \texttt{treatment} group and use
regression methods to explore whether protecting these reefs really
makes a difference compared to non-MPA sites (our control group). In
this assignment, we'll think deeply about which causal inference
assumptions hold up under the research design and identify where they
fall short.

Let's break it down step by step and see what the data reveals! 📊

\includegraphics{figures/map-5reefs.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 1: Anticipating potential sources of selection bias

\textbf{a.} Do the control sites (Arroyo Quemado, Carpenteria, and
Mohawk) provide a strong counterfactual for our treatment sites (Naples,
Isla Vista)? Write a paragraph making a case for why this comparison is
centris paribus or whether selection bias is likely (be specific!).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 2: Read \& wrangle data

\textbf{a.} Read in the raw data. Name the data.frame (\texttt{df})
\texttt{rawdata}

\textbf{b.} Use the function \texttt{clean\_names()} from the
\texttt{janitor} package

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# HINT: check for coding of missing values (\textasciigrave{}na = "{-}99999"\textasciigrave{})}
\CommentTok{\# Read in CSV, defining NAs and cleaning names}
\NormalTok{rawdata }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"spiny\_abundance\_sb\_18.csv"}\NormalTok{), }\AttributeTok{na =} \StringTok{"{-}99999"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{clean\_names}\NormalTok{()}

\CommentTok{\# Virew the dataframe to ensure it worked}
\FunctionTok{head}\NormalTok{(rawdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
##    year month date       site  transect replicate size_mm count num_ao  area
##   <dbl> <dbl> <date>     <chr>    <dbl> <chr>       <dbl> <dbl>  <dbl> <dbl>
## 1  2012     8 2012-08-20 IVEE         1 A              NA     0      0   300
## 2  2012     8 2012-08-20 IVEE         1 B              NA     0      0   300
## 3  2012     8 2012-08-20 IVEE         1 C              NA     0      0   300
## 4  2012     8 2012-08-20 IVEE         1 D              NA     0      0   300
## 5  2012     8 2012-08-20 IVEE         2 A              NA     0      0   300
## 6  2012     8 2012-08-20 IVEE         2 B              NA     0      0   300
\end{verbatim}

\textbf{c.} Create a new \texttt{df} named \texttt{tidyata}. Using the
variable \texttt{site} (reef location) create a new variable
\texttt{reef} as a \texttt{factor} and add the following labels in the
order listed (i.e., re-order the \texttt{levels}):

\begin{verbatim}
"Arroyo Quemado", "Carpenteria", "Mohawk", "Isla Vista",  "Naples"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create new dataframe }
\NormalTok{tidydata }\OtherTok{\textless{}{-}}\NormalTok{ rawdata }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{reef =} \FunctionTok{factor}\NormalTok{(site, }\AttributeTok{order =} \ConstantTok{TRUE}\NormalTok{,}
                         \AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"AQUE"}\NormalTok{,}
                                    \StringTok{"CARP"}\NormalTok{,}
                                    \StringTok{"MOHK"}\NormalTok{,}
                                    \StringTok{"IVEE"}\NormalTok{,}
                                    \StringTok{"NAPL"}\NormalTok{),}
                         \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Arroyo Quemado"}\NormalTok{,}
                                    \StringTok{"Carpinteria"}\NormalTok{,}
                                    \StringTok{"Mohawk"}\NormalTok{,}
                                    \StringTok{"Isla Vista"}\NormalTok{,}
                                    \StringTok{"Naples"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

Create new \texttt{df} named \texttt{spiny\_counts}

\textbf{d.} Create a new variable \texttt{counts} to allow for an
analysis of lobster counts where the unit-level of observation is the
total number of observed lobsters per \texttt{site}, \texttt{year} and
\texttt{transect}.

\begin{itemize}
\tightlist
\item
  Create a variable \texttt{mean\_size} from the variable
  \texttt{size\_mm}
\item
  NOTE: The variable \texttt{counts} should have values which are
  integers (whole numbers).
\item
  Make sure to account for missing cases (\texttt{na})!
\end{itemize}

\textbf{e.} Create a new variable \texttt{mpa} with levels \texttt{MPA}
and \texttt{non\_MPA}. For our regression analysis create a numerical
variable \texttt{treat} where MPA sites are coded \texttt{1} and
non\_MPA sites are coded \texttt{0}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#HINT(d): Use \textasciigrave{}group\_by()\textasciigrave{} \& \textasciigrave{}summarize()\textasciigrave{} to provide the total number of lobsters observed at each site{-}year{-}transect row{-}observation. }

\CommentTok{\#HINT(e): Use \textasciigrave{}case\_when()\textasciigrave{} to create the 3 new variable columns}

\CommentTok{\# Create new dataframe including new rows}
\NormalTok{spiny\_counts }\OtherTok{\textless{}{-}}\NormalTok{ tidydata }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{group\_by}\NormalTok{(site, year, transect) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{count =} \FunctionTok{sum}\NormalTok{(count, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
              \AttributeTok{mean\_size =} \FunctionTok{mean}\NormalTok{(size\_mm, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{mpa =} \FunctionTok{case\_when}\NormalTok{(site }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"IVEE"}\NormalTok{, }\StringTok{"NAPL"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"MPA"}\NormalTok{,}
\NormalTok{                           site }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"CARP"}\NormalTok{, }\StringTok{"MOHK"}\NormalTok{, }\StringTok{"AQUE"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"non\_MPA"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{treat =} \FunctionTok{case\_when}\NormalTok{(mpa }\SpecialCharTok{==} \StringTok{"MPA"} \SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,}
\NormalTok{                             mpa }\SpecialCharTok{==} \StringTok{"non\_MPA"} \SpecialCharTok{\textasciitilde{}} \DecValTok{0}\NormalTok{))}

\CommentTok{\# Verify the wrangling worked}
\FunctionTok{unique}\NormalTok{(spiny\_counts}\SpecialCharTok{$}\NormalTok{mpa)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "non_MPA" "MPA"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(spiny\_counts}\SpecialCharTok{$}\NormalTok{treat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0 1
\end{verbatim}

\begin{quote}
NOTE: This step is crucial to the analysis. Check with a friend or come
to TA/instructor office hours to make sure the counts are coded
correctly!
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 3: Explore \& visualize data

\textbf{a.} Take a look at the data! Get familiar with the data in each
\texttt{df} format (\texttt{tidydata}, \texttt{spiny\_counts})

\textbf{b.} We will focus on the variables \texttt{count},
\texttt{year}, \texttt{site}, and \texttt{treat}(\texttt{mpa}) to model
lobster abundance. Create the following 4 plots using a different method
each time from the 6 options provided. Add a layer (\texttt{geom}) to
each of the plots including informative descriptive statistics (you
choose; e.g., mean, median, SD, quartiles, range). Make sure each plot
dimension is clearly labeled (e.g., axes, groups).

\begin{itemize}
\tightlist
\item
  \href{https://r-charts.com/distribution/density-plot-group-ggplot2}{Density
  plot}
\item
  \href{https://r-charts.com/distribution/ggridges/}{Ridge plot}
\item
  \href{https://ggplot2.tidyverse.org/reference/geom_jitter.html}{Jitter
  plot}
\item
  \href{https://r-charts.com/distribution/violin-plot-group-ggplot2}{Violin
  plot}
\item
  \href{https://r-charts.com/distribution/histogram-density-ggplot2/}{Histogram}
\item
  \href{https://r-charts.com/distribution/beeswarm/}{Beeswarm}
\end{itemize}

Create plots displaying the distribution of lobster \textbf{counts}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  grouped by reef site\\
\item
  grouped by MPA status
\item
  grouped by year
\end{enumerate}

Create a plot of lobster \textbf{size} :

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  You choose the grouping variable(s)!
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot 1: A ridge plot grouped by reef site}
\NormalTok{spiny\_counts }\SpecialCharTok{|\textgreater{}}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ count, }\AttributeTok{y =}\NormalTok{ site)) }\SpecialCharTok{+} 
    \FunctionTok{geom\_density\_ridges}\NormalTok{(}\AttributeTok{quantile\_lines =} \ConstantTok{TRUE}\NormalTok{,}
                        \AttributeTok{quantiles =} \DecValTok{2}\NormalTok{,}
                        \AttributeTok{alpha =}\NormalTok{ .}\DecValTok{5}\NormalTok{,}
                        \AttributeTok{fill =} \StringTok{"seagreen"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{xlab}\NormalTok{(}\StringTok{"Spiny Lobster Count"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{ylab}\NormalTok{(}\StringTok{"Reef Site"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Distribution of Spiny Lobster Counts by Site"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_light}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot \#2: a beeswarm plot grouped by year}
\NormalTok{custom\_colors }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"seagreen"}\NormalTok{, }\StringTok{"yellow3"}\NormalTok{)}

\FunctionTok{beeswarm}\NormalTok{(spiny\_counts}\SpecialCharTok{$}\NormalTok{count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ spiny\_counts}\SpecialCharTok{$}\NormalTok{year,}
         \AttributeTok{pch =} \DecValTok{19}\NormalTok{,}
         \AttributeTok{pwcol =}\NormalTok{ custom\_colors[}\FunctionTok{factor}\NormalTok{(spiny\_counts}\SpecialCharTok{$}\NormalTok{mpa)],}
         \AttributeTok{xlab =} \StringTok{"Year"}\NormalTok{,}
         \AttributeTok{ylab =} \StringTok{"Lobster Count"}\NormalTok{,}
         \AttributeTok{main =} \StringTok{"Lobster Count by Year, colored by MPA Type"}\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"MPA"}\NormalTok{, }\StringTok{"non{-}MPA"}\NormalTok{),}
           \AttributeTok{col =}\NormalTok{ custom\_colors, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot \#3: Violin plot of MPA status}
\NormalTok{spiny\_counts }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{count, }\AttributeTok{y=}\NormalTok{mpa)) }\SpecialCharTok{+}
    \FunctionTok{geom\_violin}\NormalTok{(}\AttributeTok{color =} \StringTok{"seagreen"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"seagreen"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{draw\_quantiles =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.25}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.75}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{xlab}\NormalTok{(}\StringTok{"Lobster Count"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{ylab}\NormalTok{(}\StringTok{"MPA Status"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Count of Spiny Lobster grouped by MPA status"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_light}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot \#4: Stacked Bar Plot of lobster size}
\NormalTok{spiny\_counts }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{mean\_size, }\AttributeTok{fill =}\NormalTok{ mpa)) }\SpecialCharTok{+}
    \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{xlab}\NormalTok{(}\StringTok{"Mean Size of Spiny Lobster (mm)"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{ylab}\NormalTok{(}\StringTok{"Spiny Lobster Count"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Size Distribution of Spiny Lobsters, by MPA Status"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_light}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-8-1.pdf}

\textbf{c.} Compare means of the outcome by treatment group. Using the
\texttt{tbl\_summary()} function from the package
\href{https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html}{\texttt{gt\_summary}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# USE: gt\_summary::tbl\_summary()}
\CommentTok{\# Compare the means of the counts by treatment group}
\NormalTok{spiny\_counts }\SpecialCharTok{|\textgreater{}} 
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(treat, count) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{tbl\_summary}\NormalTok{(}
        \AttributeTok{by =}\NormalTok{ treat,}
        \AttributeTok{statistic =} \FunctionTok{list}\NormalTok{(}\FunctionTok{all\_continuous}\NormalTok{() }\SpecialCharTok{\textasciitilde{}} \StringTok{"\{mean\} (\{sd\})"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}} 
    \FunctionTok{modify\_header}\NormalTok{(label }\SpecialCharTok{\textasciitilde{}} \StringTok{"**Variable**"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{modify\_spanning\_header}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"stat\_1"}\NormalTok{, }\StringTok{"stat\_2"}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"**Treatment**"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{table}[!t]
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcc}
\toprule
 & \multicolumn{2}{c}{\textbf{Treatment}} \\ 
\cmidrule(lr){2-3}
\textbf{Variable} & \textbf{0}  N = 133\textsuperscript{\textit{1}} & \textbf{1}  N = 119\textsuperscript{\textit{1}} \\ 
\midrule\addlinespace[2.5pt]
site &  &  \\ 
    AQUE & 49 (37\%) & 0 (0\%) \\ 
    CARP & 63 (47\%) & 0 (0\%) \\ 
    IVEE & 0 (0\%) & 56 (47\%) \\ 
    MOHK & 21 (16\%) & 0 (0\%) \\ 
    NAPL & 0 (0\%) & 63 (53\%) \\ 
year &  &  \\ 
    2012 & 19 (14\%) & 17 (14\%) \\ 
    2013 & 19 (14\%) & 17 (14\%) \\ 
    2014 & 19 (14\%) & 17 (14\%) \\ 
    2015 & 19 (14\%) & 17 (14\%) \\ 
    2016 & 19 (14\%) & 17 (14\%) \\ 
    2017 & 19 (14\%) & 17 (14\%) \\ 
    2018 & 19 (14\%) & 17 (14\%) \\ 
count & 23 (39) & 28 (44) \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\textsuperscript{\textit{1}}n (\%); Mean (SD)\\
\end{minipage}
\end{table}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 4: OLS regression- building intuition

\textbf{a.} Start with a simple OLS estimator of lobster counts
regressed on treatment. Use the function \texttt{summ()} from the
\href{https://jtools.jacob-long.com/}{\texttt{jtools}} package to print
the OLS output

\textbf{b.} Interpret the intercept \& predictor coefficients \emph{in
your own words}. Use full sentences and write your interpretation of the
regression results to be as clear as possible to a non-academic
audience.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: We will not evaluate/interpret model fit in this assignment (e.g., R{-}square)}

\NormalTok{m1\_ols }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treat, spiny\_counts)}

\FunctionTok{summ}\NormalTok{(m1\_ols, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{252}\\
Dependent variable & count\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{OLS linear regression}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & t val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{22.73} & \cellcolor{gray!10}{3.57} & \cellcolor{gray!10}{6.36} & \cellcolor{gray!10}{0.00}\\
treat & 5.36 & 5.20 & 1.03 & 0.30\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: OLS
\end{tablenotes}
\end{threeparttable}
\end{table}

\textbf{The intercept coefficient represents the number of lobster
counts with the treatment group is 0. Since our treatment group is the
not-MPA group, this analysis tells us that there is 22.73 lobsters on
average in not MPAs, so there are 5.36 more lobsters on average in the
MPA group. The p-value is above the .05 threshold for statistical
significance.}

\textbf{c.} Check the model assumptions using the \texttt{check\_model}
function from the \texttt{performance} package

\textbf{d.} Explain the results of the 4 diagnostic plots. Why are we
getting this result?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m1\_ols,  }\AttributeTok{check =} \StringTok{"qq"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m1\_ols, }\AttributeTok{check =} \StringTok{"normality"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m1\_ols, }\AttributeTok{check =} \StringTok{"homogeneity"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m1\_ols, }\AttributeTok{check =} \StringTok{"pp\_check"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-14-1.pdf}

\subsection{\texorpdfstring{\textbf{These four plots show that the data
are not normally distributed. The data seems to be right skewed. So, we
assume that there is a violation in the assumptions of OLS. The lm() is
probably not the best model to use on this data as a
result.}}{These four plots show that the data are not normally distributed. The data seems to be right skewed. So, we assume that there is a violation in the assumptions of OLS. The lm() is probably not the best model to use on this data as a result.}}\label{these-four-plots-show-that-the-data-are-not-normally-distributed.-the-data-seems-to-be-right-skewed.-so-we-assume-that-there-is-a-violation-in-the-assumptions-of-ols.-the-lm-is-probably-not-the-best-model-to-use-on-this-data-as-a-result.}

Step 5: Fitting GLMs

\textbf{a.} Estimate a Poisson regression model using the \texttt{glm()}
function

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#HINT1: Incidence Ratio Rate (IRR): Exponentiation of beta returns coefficient which is interpreted as the \textquotesingle{}percent change\textquotesingle{} for a one unit increase in the predictor }

\CommentTok{\#HINT2: For the second glm() argument \textasciigrave{}family\textasciigrave{} use the following specification option \textasciigrave{}family = poisson(link = "log")\textasciigrave{}}

\CommentTok{\# Run a Poissoin model}
\NormalTok{m2\_pois }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treat,}
               \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
               \AttributeTok{data =}\NormalTok{ spiny\_counts)}

\CommentTok{\# Print the output}
\FunctionTok{summ}\NormalTok{(m2\_pois, }\AttributeTok{model.fit=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{252}\\
Dependent variable & count\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{Generalized linear model}\\
Family & poisson\\
\cellcolor{gray!10}{Link} & \cellcolor{gray!10}{log}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & z val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{3.12} & \cellcolor{gray!10}{0.02} & \cellcolor{gray!10}{171.74} & \cellcolor{gray!10}{0.00}\\
treat & 0.21 & 0.03 & 8.44 & 0.00\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: MLE
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Code the IRR, Incidence Ratio Rate}
\FunctionTok{exp}\NormalTok{(m2\_pois}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]) }\SpecialCharTok{{-}}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     treat 
## 0.2359557
\end{verbatim}

\textbf{b.} Interpret the predictor coefficient in your own words. Use
full sentences and write your interpretation of the results to be as
clear as possible to a non-academic audience.

\textbf{By calculating the IRR, we can see that there is a 23.5\%
increase in lobster counts in MPA group, vs the non-MPA group.}

\textbf{c.} Explain the statistical concept of dispersion and
overdispersion in the context of this model.

\textbf{One of the assumptions of Poisson regression is that variance is
proportional to the mean. So, if the data is super dispersed, than the
variance is greater than the mean.}

\textbf{d.} Compare results with previous model, explain change in the
significance of the treatment effect

\textbf{In the lm() model, there was 5.36 more lobsters on average
within MPAs compared to outside of them. In the Poisson model, there is
slightly less than that, so the relationship between lobster counts
inside vs outside MPAs is slightly less dramatic.}

\textbf{e.} Check the model assumptions. Explain results.

\textbf{After running the analysis below, I can see that Poisson is also
likely not a good fit for this data. When measuring uniformity of
residuals, the dots do not fall along the line. The homogenity of
variance looks better, as the reference line is flat and horizontal.
However, in the chart showing misspecified dispersion and
zero-inflation, the green line does not follow the line of the predicted
mean. So, it seems like I am violating some of the assumptions of the
Poisson model.}

\textbf{f.} Conduct tests for over-dispersion \& zero-inflation. Explain
results.

\textbf{I ran these tests below. The tests show that the model is
predicint less zeros than are actually present in the data. So, there
may be zero inflation. The dispersion test shows that the variance is
significantly larger than the mean, which means we are violating one of
the assumptions, and the model is not the best fit.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m2\_pois)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_overdispersion}\NormalTok{(m2\_pois)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Overdispersion test
## 
##        dispersion ratio =    67.033
##   Pearson's Chi-Squared = 16758.289
##                 p-value =   < 0.001
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_zeroinflation}\NormalTok{(m2\_pois)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Check for zero-inflation
## 
##    Observed zeros: 27
##   Predicted zeros: 0
##             Ratio: 0.00
\end{verbatim}

\textbf{g.} Fit a negative binomial model using the function glm.nb()
from the package \texttt{MASS} and check model diagnostics

\textbf{I ran this in the provided code chunk below}

\textbf{h.} In 1-2 sentences explain rationale for fitting this GLM
model.

\textbf{This is a negative binomial regression model. It is a model that
allows us to relax the assumption that the variance is equal to the
mean. Since the variance is not equal to the mean in our data, this
model may be a better choice for this analysis}

\textbf{i.} Interpret the treatment estimate result in your own words.
Compare with results from the previous model.

\textbf{This model shows that there is a 23\% increase in lobsters
within MPAs, compared to outside. This is extremely similar to our
previous model. Wheb we do our checks below, however, we can see that
this model does a much better job with over dispersion and zero
inflation.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: The \textasciigrave{}glm.nb()\textasciigrave{} function does not require a \textasciigrave{}family\textasciigrave{} argument}
\CommentTok{\# Run the model}
\NormalTok{m3\_nb }\OtherTok{\textless{}{-}} \FunctionTok{glm.nb}\NormalTok{(count }\SpecialCharTok{\textasciitilde{}}\NormalTok{ treat, spiny\_counts)}

\CommentTok{\# Print results}
\FunctionTok{summ}\NormalTok{(m3\_nb, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{252}\\
Dependent variable & count\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{Generalized linear model}\\
Family & Negative Binomial(0.55)\\
\cellcolor{gray!10}{Link} & \cellcolor{gray!10}{log}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & z val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{3.12} & \cellcolor{gray!10}{0.12} & \cellcolor{gray!10}{26.40} & \cellcolor{gray!10}{0.00}\\
treat & 0.21 & 0.17 & 1.23 & 0.22\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: MLE
\end{tablenotes}
\end{threeparttable}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculate IRR}
\FunctionTok{exp}\NormalTok{(m2\_pois}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]) }\SpecialCharTok{{-}}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     treat 
## 0.2359557
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_overdispersion}\NormalTok{(m3\_nb)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Overdispersion test
## 
##  dispersion ratio = 1.398
##           p-value = 0.088
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_zeroinflation}\NormalTok{(m3\_nb)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Check for zero-inflation
## 
##    Observed zeros: 27
##   Predicted zeros: 30
##             Ratio: 1.12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_predictions}\NormalTok{(m3\_nb)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(m3\_nb)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 6: Compare models

\textbf{a.} Use the \texttt{export\_summ()} function from the
\texttt{jtools} package to look at the three regression models you fit
side-by-side.

\textbf{c.} Write a short paragraph comparing the results. Is the
treatment effect \texttt{robust} or stable across the model
specifications.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Made a table comparing the models}
\FunctionTok{export\_summs}\NormalTok{(m1\_ols, m2\_pois, m3\_nb,}
             \AttributeTok{model.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"OLS"}\NormalTok{,}\StringTok{"Poisson"}\NormalTok{, }\StringTok{"NB"}\NormalTok{),}
             \AttributeTok{statistics =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

 
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
\begin{threeparttable}
 \setlength{\tabcolsep}{0pt}
\begin{tabular}{l l l l}


\hhline{>{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\centering \hspace{6pt}  \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\centering \hspace{6pt} OLS \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\centering \hspace{6pt} Poisson \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\centering \hspace{6pt} NB \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{255, 255, 255}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} (Intercept) \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 22.73 *** \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 3.12 *** \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 3.12 *** \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt}  \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (3.57)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (0.02)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (0.12)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} treat \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 5.36\hphantom{0}\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 0.21 *** \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 0.21\hphantom{0}\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt}  \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (5.20)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (0.03)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} (0.17)\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}-}
\arrayrulecolor{black}

\multicolumn{4}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt}  *** p $<$ 0.001;  ** p $<$ 0.01;  * p $<$ 0.05. \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}
\end{tabular}
\end{threeparttable}\par\end{centerbox}

\end{table}
 

\subsection{\texorpdfstring{\textbf{It seems to me that in all three
models, there is a ``robust'' treatment effect between the two groups.
Or, the relationship between MPAs and non-MPAs is stable across the
model
specifications.}}{It seems to me that in all three models, there is a ``robust'' treatment effect between the two groups. Or, the relationship between MPAs and non-MPAs is stable across the model specifications.}}\label{it-seems-to-me-that-in-all-three-models-there-is-a-robust-treatment-effect-between-the-two-groups.-or-the-relationship-between-mpas-and-non-mpas-is-stable-across-the-model-specifications.}

Step 7: Building intuition - fixed effects

\textbf{a.} Create new \texttt{df} with the \texttt{year} variable
converted to a factor

\textbf{b.} Run the following OLS model using \texttt{lm()}

\begin{itemize}
\tightlist
\item
  Use the following specification for the outcome \texttt{log(counts+1)}
\item
  Estimate fixed effects for \texttt{year}
\item
  Include an interaction term between variables \texttt{treat} and
  \texttt{year}
\end{itemize}

\textbf{c.} Take a look at the regression output. Each coefficient
provides a comparison or the difference in means for a specific
sub-group in the data. Informally, describe the what the model has
estimated at a conceptual level (NOTE: you do not have to interpret
coefficients individually)

\textbf{This model is predicting how the effect on lobster count varies
year to year, considering the treatment.}

\textbf{d.} Explain why the main effect for treatment is negative? *Does
this result make sense?

\textbf{If it is negative, it means that the treatment groups had lower
lobster counts compared to the control group. It is ok if it is
negative, because it is showing a reduction.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ff\_counts }\OtherTok{\textless{}{-}}\NormalTok{ spiny\_counts }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{year=}\FunctionTok{as\_factor}\NormalTok{(year))}
    
\NormalTok{m5\_fixedeffs }\OtherTok{\textless{}{-}} \FunctionTok{glm.nb}\NormalTok{(}
\NormalTok{    count }\SpecialCharTok{\textasciitilde{}} 
\NormalTok{        treat }\SpecialCharTok{+} 
\NormalTok{        year }\SpecialCharTok{+}
\NormalTok{        treat}\SpecialCharTok{*}\NormalTok{year,}
    \AttributeTok{data =}\NormalTok{ ff\_counts)}

\FunctionTok{summ}\NormalTok{(m5\_fixedeffs, }\AttributeTok{model.fit =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\begin{tabular}{lr}
\toprule
\cellcolor{gray!10}{Observations} & \cellcolor{gray!10}{252}\\
Dependent variable & count\\
\cellcolor{gray!10}{Type} & \cellcolor{gray!10}{Generalized linear model}\\
Family & Negative Binomial(0.8129)\\
\cellcolor{gray!10}{Link} & \cellcolor{gray!10}{log}\\
\bottomrule
\end{tabular}
\end{table}  \begin{table}[!h]
\centering
\begin{threeparttable}
\begin{tabular}{lrrrr}
\toprule
  & Est. & S.E. & z val. & p\\
\midrule
\cellcolor{gray!10}{(Intercept)} & \cellcolor{gray!10}{2.35} & \cellcolor{gray!10}{0.26} & \cellcolor{gray!10}{8.89} & \cellcolor{gray!10}{0.00}\\
treat & -1.72 & 0.42 & -4.12 & 0.00\\
\cellcolor{gray!10}{year2013} & \cellcolor{gray!10}{-0.35} & \cellcolor{gray!10}{0.38} & \cellcolor{gray!10}{-0.93} & \cellcolor{gray!10}{0.35}\\
year2014 & 0.08 & 0.37 & 0.21 & 0.84\\
\cellcolor{gray!10}{year2015} & \cellcolor{gray!10}{0.86} & \cellcolor{gray!10}{0.37} & \cellcolor{gray!10}{2.32} & \cellcolor{gray!10}{0.02}\\
\addlinespace
year2016 & 0.90 & 0.37 & 2.43 & 0.01\\
\cellcolor{gray!10}{year2017} & \cellcolor{gray!10}{1.56} & \cellcolor{gray!10}{0.37} & \cellcolor{gray!10}{4.25} & \cellcolor{gray!10}{0.00}\\
year2018 & 1.04 & 0.37 & 2.81 & 0.00\\
\cellcolor{gray!10}{treat:year2013} & \cellcolor{gray!10}{1.52} & \cellcolor{gray!10}{0.57} & \cellcolor{gray!10}{2.66} & \cellcolor{gray!10}{0.01}\\
treat:year2014 & 2.14 & 0.56 & 3.80 & 0.00\\
\addlinespace
\cellcolor{gray!10}{treat:year2015} & \cellcolor{gray!10}{2.12} & \cellcolor{gray!10}{0.56} & \cellcolor{gray!10}{3.79} & \cellcolor{gray!10}{0.00}\\
treat:year2016 & 1.40 & 0.56 & 2.50 & 0.01\\
\cellcolor{gray!10}{treat:year2017} & \cellcolor{gray!10}{1.55} & \cellcolor{gray!10}{0.56} & \cellcolor{gray!10}{2.77} & \cellcolor{gray!10}{0.01}\\
treat:year2018 & 2.62 & 0.56 & 4.69 & 0.00\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Standard errors: MLE
\end{tablenotes}
\end{threeparttable}
\end{table}

\textbf{e.} Look at the model predictions: Use the
\texttt{interact\_plot()} function from package \texttt{interactions} to
plot mean predictions by year and treatment status.

\textbf{f.} Re-evaluate your responses (c) and (b) above.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Hint 1: Group counts by \textasciigrave{}year\textasciigrave{} and \textasciigrave{}mpa\textasciigrave{} and calculate the \textasciigrave{}mean\_count\textasciigrave{}}
\CommentTok{\# Hint 2: Convert variable \textasciigrave{}year\textasciigrave{} to a factor}

\CommentTok{\# Plot the predicted outcomes}
\FunctionTok{interact\_plot}\NormalTok{(m5\_fixedeffs, }\AttributeTok{pred =}\NormalTok{ year, }\AttributeTok{modx =}\NormalTok{ treat,}
              \AttributeTok{outcome.scale =} \StringTok{"link"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-26-1.pdf}

\textbf{Looking at the above analysis, it looks like the two groups have
different y intercepts, which may be affecting the results.}

\textbf{g.} Using \texttt{ggplot()} create a plot in same style as the
previous \texttt{interaction\ plot}, but displaying the original scale
of the outcome variable (lobster counts). This type of plot is commonly
used to show how the treatment effect changes across discrete time
points (i.e., panel data).

The plot should have\ldots{} - \texttt{year} on the x-axis -
\texttt{counts} on the y-axis - \texttt{mpa} as the grouping variable

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Hint 1: Group counts by \textasciigrave{}year\textasciigrave{} and \textasciigrave{}mpa\textasciigrave{} and calculate the \textasciigrave{}mean\_count\textasciigrave{}}
\CommentTok{\# Hint 2: Convert variable \textasciigrave{}year\textasciigrave{} to a factor}

\CommentTok{\# Group by to make data plottable, and plot}
\NormalTok{plot\_counts }\OtherTok{\textless{}{-}}\NormalTok{ spiny\_counts }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{group\_by}\NormalTok{(year, mpa) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{mean\_count =} \FunctionTok{mean}\NormalTok{(count, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ mean\_count, }\AttributeTok{color =}\NormalTok{ mpa)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme\_light}\NormalTok{()}

\NormalTok{plot\_counts}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw1-lobstrs-eds241_files/figure-latex/unnamed-chunk-27-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Step 8: Reconsider causal identification assumptions

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Discuss whether you think \texttt{spillover\ effects} are likely in
  this research context (see Glossary of terms;
  \url{https://docs.google.com/document/d/1RIudsVcYhWGpqC-Uftk9UTz3PIq6stVyEpT44EPNgpE/edit?usp=sharing})
\end{enumerate}

\textbf{Because lobsters can swim, and are not strictly confined to any
specific location, unless there was specific tagging of lobsters
happening, then the spillover potential is high.}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Explain why spillover is an issue for the identification of causal
  effects
\end{enumerate}

\textbf{This can effect identification of causal effects, because if the
control and treatment groups mix, then it violates the assumptions of
the models.}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  How does spillover relate to impact in this research setting?
\end{enumerate}

\textbf{In this research setting, it could impact analysis of the
effectiveness of MPAs. Knowing the setting is important to determine
which statistical methods are best.}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\item
  Discuss the following causal inference assumptions in the context of
  the MPA treatment effect estimator. Evaluate if each of the assumption
  are reasonable:

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii})}
  \tightlist
  \item
    SUTVA: Stable Unit Treatment Value assumption
  \end{enumerate}

  \textbf{SUTVA requires no interference, and no hidden variations in
  the treatment. It would not hold up with this experiment, given the
  spillover issues discussed earlier, as well as the fact that there
  might be variations within each MPA in terms of management.}

  \begin{enumerate}
  \def\labelenumii{\arabic{enumii})}
  \setcounter{enumii}{1}
  \tightlist
  \item
    Excludability assumption ** This assumption assumes that there are
    no other causal effects in play. This is probably not possible in
    our study, as there are many variables that might be affecting the
    lobsters, not just MPA designation.**
    ------------------------------------------------------------------------
  \end{enumerate}
\end{enumerate}

\section{EXTRA CREDIT}\label{extra-credit}

\begin{quote}
Use the recent lobster abundance data with observations collected up
until 2024 (\texttt{lobster\_sbchannel\_24.csv}) to run an analysis
evaluating the effect of MPA status on lobster counts using the same
focal variables.
\end{quote}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new script for the analysis on the updated data
\item
  Run at least 3 regression models \& assess model diagnostics
\item
  Compare and contrast results with the analysis from the 2012-2018 data
  sample (\textasciitilde{} 2 paragraphs)
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{figures/spiny1.png}

\end{document}
